name: FakePlayers
main: me.KP56.FakePlayers.Main
version: 2.5
author: KP56

api-version: 1.19

softdepend: [ProtocolLib, FastLogin, AuthMe, HamsterAPI, NexEngine, CustomDisplay]

commands:
  fakeplayers: